### ISSUE TITLE
load_osxfuse should fall back to earlier versions if not found

### ISSUE THREAD

**Issue by gabriel** [osxfuse/support#3]
If you have 10.12 installed (theoretically) load_kbfuse would fail since there
is no symlink or kext in `/Library/Filesystems/osxfuse.fs/Contents/Extensions/10.12`

It would be nice to have load_osxfuse attempt to find earlier versions.

**Comment by bfleischer** [comment]
The FUSE kernel extension relies on private API and includes some hacks to get the job done. Loading an earlier version of the kernel extension on a newer version of OS X can result in kernel panics. Adding a 10.12 symlink without having verified there are no compatibility issues on the real 10.12 is risky.

In the past, new versions of osxfuse with (experimental) support for upcoming versions of OS X have been available one or two weeks after the first OS X developer preview became available.
