### ISSUE TITLE
Black Sidebar Icon

### ISSUE THREAD

**Issue by true-Grand** [osxfuse/support#7]
I Don't Know where to put this so hopefully someone sees this and fix it
<img width="135" alt="Screen Shot 2021-11-08 at 8 38 56 PM" src="https://user-images.githubusercontent.com/78011648/140743698-edad866c-eaae-4666-94d4-06a4df3133ed.png">
. A mounted drive using Fuse isn't displaying a proper sidebar icon. Hopefully someone can fix it..

**Comment by bfleischer** [comment]
Duplicate, closed
